"""empty message

Revision ID: 664686f51e3f
Revises: cd6c73e28df3
Create Date: 2021-01-28 04:43:23.417594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664686f51e3f'
down_revision = 'cd6c73e28df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
