"""empty message

Revision ID: df72671ace67
Revises: 664686f51e3f
Create Date: 2021-01-28 04:49:18.783029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df72671ace67'
down_revision = '664686f51e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pictures', sa.PickleType(), nullable=True))
        batch_op.drop_column('photos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.BLOB(), nullable=True))
        batch_op.drop_column('pictures')

    # ### end Alembic commands ###
